# Site settings
title: "здесь должен быть заголовок"
email: devpo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl:  # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: devpo
github_username: jazzok

# Build settings
markdown: kramdown
